-- OneLine Cinema: additive, standalone movie tables. Does NOT modify restaurant tables.
-- Run in the SAME Supabase project as the existing app, via SQL Editor.
-- Re-runnable for this app's own policies/functions. Existing restaurant data is preserved.
begin;

create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 120),
  release_year integer not null check (release_year between 1888 and 2100),
  genres text[] not null check (
    cardinality(genres) between 1 and 3
    and genres <@ array[
      'Action','Animation','Comedy','Crime','Documentary','Drama',
      'Fantasy','Horror','Mystery','Romance','Sci-Fi','Thriller'
    ]::text[]
  ),
  poster_path text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint movie_poster_owner_path check (
    poster_path is null or created_by is null or (
      poster_path like created_by::text || '/%'
      and char_length(poster_path) <= 220
    )
  )
);
create unique index if not exists movies_unique_title_year
  on public.movies (lower(trim(title)), release_year);
create index if not exists movies_recent on public.movies (created_at desc);
alter table public.movies enable row level security;
revoke all on public.movies from anon, authenticated;
grant select on public.movies to anon, authenticated;
grant insert (title, release_year, genres, poster_path, created_by) on public.movies to authenticated;
grant update (title, release_year, genres, poster_path) on public.movies to authenticated;
grant delete on public.movies to authenticated;
do $$ declare seq text; begin
  seq := pg_get_serial_sequence('public.movies', 'id');
  if seq is not null then
    execute format('grant usage on sequence %s to authenticated', seq);
  end if;
end $$;
drop policy if exists movies_public_read on public.movies;
drop policy if exists movies_insert_own on public.movies;
drop policy if exists movies_update_own on public.movies;
drop policy if exists movies_delete_own on public.movies;
create policy movies_public_read on public.movies
  for select to anon, authenticated using (true);
create policy movies_insert_own on public.movies
  for insert to authenticated with check (created_by = (select auth.uid()));
create policy movies_update_own on public.movies
  for update to authenticated using (created_by = (select auth.uid()))
  with check (created_by = (select auth.uid()));
create policy movies_delete_own on public.movies
  for delete to authenticated using (created_by = (select auth.uid()));

-- The original long thoughts and all three generated options stay PRIVATE.
create table if not exists public.movie_review_drafts (
  id uuid primary key default gen_random_uuid(),
  movie_id bigint not null references public.movies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  impression text not null check (char_length(impression) between 20 and 5000),
  tone text not null check (tone in ('Witty','Serious','Poetic','Sarcastic')),
  spoiler_free boolean not null default true,
  candidates text[] not null check (cardinality(candidates) = 3),
  model text not null check (char_length(model) between 1 and 100),
  created_at timestamptz not null default now(),
  published_at timestamptz
);
create index if not exists movie_drafts_user_idx
  on public.movie_review_drafts(user_id, created_at desc);
alter table public.movie_review_drafts enable row level security;
revoke all on public.movie_review_drafts from anon, authenticated;
grant select on public.movie_review_drafts to authenticated;
grant insert (movie_id, user_id, impression, tone, spoiler_free, candidates, model)
  on public.movie_review_drafts to authenticated;
drop policy if exists movie_drafts_own_read on public.movie_review_drafts;
drop policy if exists movie_drafts_own_insert on public.movie_review_drafts;
create policy movie_drafts_own_read on public.movie_review_drafts
  for select to authenticated using (user_id = (select auth.uid()));
create policy movie_drafts_own_insert on public.movie_review_drafts
  for insert to authenticated with check (user_id = (select auth.uid()));

-- The published one-liner alone is public. Clients cannot write review rows directly.
create table if not exists public.movie_reviews (
  id uuid primary key default gen_random_uuid(),
  draft_id uuid not null unique references public.movie_review_drafts(id) on delete cascade,
  movie_id bigint not null references public.movies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  one_liner text not null check (char_length(one_liner) between 1 and 160),
  tone text not null check (tone in ('Witty','Serious','Poetic','Sarcastic')),
  created_at timestamptz not null default now()
);
create index if not exists movie_reviews_movie_idx
  on public.movie_reviews(movie_id, created_at desc);
alter table public.movie_reviews enable row level security;
revoke all on public.movie_reviews from anon, authenticated;
grant select (id, movie_id, one_liner, tone, created_at)
  on public.movie_reviews to anon, authenticated;
drop policy if exists movie_reviews_public_read on public.movie_reviews;
create policy movie_reviews_public_read on public.movie_reviews
  for select to anon, authenticated using (true);

create table if not exists public.movie_review_votes (
  review_id uuid not null references public.movie_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  value smallint not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  primary key (review_id, user_id)
);
create index if not exists movie_votes_user_idx on public.movie_review_votes(user_id);
alter table public.movie_review_votes enable row level security;
revoke all on public.movie_review_votes from anon, authenticated;
grant select, delete on public.movie_review_votes to authenticated;
grant insert (review_id, user_id, value) on public.movie_review_votes to authenticated;
grant update (value) on public.movie_review_votes to authenticated;
drop policy if exists movie_votes_read_own on public.movie_review_votes;
drop policy if exists movie_votes_insert_own on public.movie_review_votes;
drop policy if exists movie_votes_update_own on public.movie_review_votes;
drop policy if exists movie_votes_delete_own on public.movie_review_votes;
create policy movie_votes_read_own on public.movie_review_votes
  for select to authenticated using (user_id = (select auth.uid()));
create policy movie_votes_insert_own on public.movie_review_votes
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy movie_votes_update_own on public.movie_review_votes
  for update to authenticated using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));
create policy movie_votes_delete_own on public.movie_review_votes
  for delete to authenticated using (user_id = (select auth.uid()));

-- Only the selected stored candidate can become public. Selection is atomic and once-only.
create or replace function public.publish_movie_review(
  p_draft_id uuid, p_selection integer
) returns uuid
language plpgsql security definer set search_path = '' as $$
declare
  d public.movie_review_drafts%rowtype;
  new_review_id uuid;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_selection not between 0 and 2 then raise exception 'Invalid candidate selection'; end if;
  select * into d from public.movie_review_drafts
    where id = p_draft_id and user_id = auth.uid() for update;
  if not found then raise exception 'Draft not found'; end if;
  if d.published_at is not null then raise exception 'Already published'; end if;
  if char_length(d.candidates[p_selection + 1]) not between 1 and 160 then
    raise exception 'Invalid one-liner';
  end if;
  insert into public.movie_reviews (draft_id, movie_id, user_id, one_liner, tone)
    values (d.id, d.movie_id, d.user_id, d.candidates[p_selection + 1], d.tone)
    returning id into new_review_id;
  update public.movie_review_drafts set published_at = now() where id = d.id;
  return new_review_id;
end $$;
revoke all on function public.publish_movie_review(uuid, integer) from public;
grant execute on function public.publish_movie_review(uuid, integer) to authenticated;

-- Aggregate counts never expose individual voters.
create or replace function public.movie_review_scores()
returns table (review_id uuid, upvotes bigint, downvotes bigint)
language sql stable security definer set search_path = '' as $$
  select r.id,
    count(v.review_id) filter (where v.value = 1),
    count(v.review_id) filter (where v.value = -1)
  from public.movie_reviews r
  left join public.movie_review_votes v on v.review_id = r.id
  group by r.id;
$$;
revoke all on function public.movie_review_scores() from public;
grant execute on function public.movie_review_scores() to anon, authenticated;

create table if not exists public.movie_generation_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  day date not null,
  attempts integer not null check (attempts between 1 and 10),
  primary key (user_id, day)
);
alter table public.movie_generation_usage enable row level security;
revoke all on public.movie_generation_usage from anon, authenticated;
create or replace function public.claim_movie_generation_attempt()
returns boolean language plpgsql security definer set search_path = '' as $$
declare used integer; begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  insert into public.movie_generation_usage(user_id, day, attempts)
    values (auth.uid(), (now() at time zone 'America/New_York')::date, 1)
    on conflict (user_id, day) do update
      set attempts = public.movie_generation_usage.attempts + 1
      where public.movie_generation_usage.attempts < 10
    returning attempts into used;
  return used is not null;
end $$;
revoke all on function public.claim_movie_generation_attempt() from public;
grant execute on function public.claim_movie_generation_attempt() to authenticated;

-- Only licensed/original images may be uploaded. No third-party poster API is used.
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('movie-posters','movie-posters',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update
  set public = true, file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;
drop policy if exists movie_poster_upload on storage.objects;
drop policy if exists movie_poster_own_read on storage.objects;
drop policy if exists movie_poster_own_delete on storage.objects;
create policy movie_poster_upload on storage.objects
  for insert to authenticated with check (
    bucket_id = 'movie-posters'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
  );
create policy movie_poster_own_read on storage.objects
  for select to authenticated using (
    bucket_id = 'movie-posters'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
  );
create policy movie_poster_own_delete on storage.objects
  for delete to authenticated using (
    bucket_id = 'movie-posters'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
  );

-- Optional starter catalog uses film titles/factual metadata only, no copyrighted art.
insert into public.movies(title,release_year,genres) values
  ('Interstellar', 2014, array['Sci-Fi','Drama']),
  ('Parasite', 2019, array['Thriller','Drama']),
  ('The Truman Show', 1998, array['Drama','Comedy']),
  ('Spirited Away', 2001, array['Animation','Fantasy']),
  ('Everything Everywhere All at Once', 2022, array['Sci-Fi','Comedy']),
  ('The Dark Knight', 2008, array['Action','Crime'])
on conflict do nothing;

commit;
